services:
  worldmap:
    container_name: worldmap
    image: worldmap
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Map the host AIS_API_KEY to the container
      - AIS_API_KEY=${AIS_API_KEY}
      - TZ=Pacific/Auckland
    restart: unless-stopped
    volumes:
      - ./data:/opt/project/data
      - ./scripts:/opt/project/scripts
      - ./config:/opt/project/config
    healthcheck:
      # Specifically check for an updated file in the data directory
      test: ["CMD", "find", "/opt/project/data/quake_markers.txt", "-mmin", "-30"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m
