#!/bin/bash
set -e

# Get the home/root application directory
HOME=$(pwd)
CONFIG=${HOME}/config
WORLDMAP_CONFIG_FILE=${CONFIG}/worldmap.conf
if [ ! -f ${WORLDMAP_CONFIG_FILE} ] ; then
  echo "No config at ${WORLDMAP_CONFIG_FILE} - is WorldMap installed properly?"
  exit 1
fi
DATA=${HOME}/data
SCRIPTS=${HOME}/scripts
VENV=${HOME}/.venv
PYTHON3=${VENV}/bin/python3

export HOME CONFIG WORLDMAP_CONFIG_FILE DATA SCRIPTS VENV PYTHON3