[earth]
"Earth"
map=resources/day_map_realistic_outline.jpg
night_map=resources/night_map_realistic_outline.jpg
specular_map=resources/earthspec.jpg
cloud_map=data/cloud_map_with_isobars.jpg
cloud_threshold=200
cloud_gamma=0.7
marker_color=cyan
marker_file=resources/city_markers.txt
marker_file=data/storm_markers.txt
marker_file=data/quake_markers.txt
marker_file=data/volcano_markers.txt
marker_file=data/ship_markers.txt
marker_fontsize=10
